# Generated by Django 3.2 on 2022-09-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_phone_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetoken',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
