# Generated by Django 4.2.3 on 2023-09-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_phone_login', '0002_remove_phonetoken_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetoken',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
