# Generated by Django 4.2.3 on 2023-09-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_phone_login', '0003_alter_phonetoken_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonetoken',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
